export const ADD_NEW_TODO = 'ADD_NEW_TODO';
export const ADD_NEW_TODO_SUCCESS = 'ADD_NEW_TODO_SUCCESS';
export const ADD_NEW_TODO_FAILURE = 'ADD_NEW_TODO_FAILURE';

export const DEL_TODO = 'DEL_TODO';
export const DEL_TODO_SUCCESS = 'DEL_TODO_SUCCESS';
export const DEL_TODO_FAILURE = 'DEL_TODO_FAILURE';

export const UPDATE_TODO = 'UPDATE_TODO';
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
export const UPDATE_TODO_FAILURE = 'UPDATE_TODO_FAILURE';

export const MARK_COMPLETE = 'MARK_COMPLETE';
export const MARK_COMPLETE_SUCCESS = 'MARK_COMPLETE_SUCCESS';
export const MARK_COMPLETE_FAILURE = 'MARK_COMPLETE_FAILURE';

export const GET_TODOS = 'GET_TODOS';
export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS';
export const GET_TODOS_FAILURE = 'GET_TODOS_FAILURE';

export const LOGGING_IN = 'LOGGING_IN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
